package cn.II_readyJobClass.Day_5_异常检测.父类子类抛异常测试;

public class FuClass {

    public void methodFu() throws Exception{
        int[] a = null;
        int i = a[1];
    }

}
